// utils/previewembed.js
const { EmbedBuilder } = require('discord.js');

function createPreviewEmbed({ title, description, image, fields }) {
  const embed = new EmbedBuilder()
    .setTitle(title || 'Default Title')
    .setDescription(description || 'No description provided.')
    .setColor('#00FFCC')
    .setFooter({ text: 'Generated by Shimas' })
    .setTimestamp();

  if (image) embed.setImage(image);
  if (fields && Array.isArray(fields)) embed.addFields(fields);

  return embed;
}

module.exports = { createPreviewEmbed };
